name: Provision Tool Infra
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        TF_LOG: DEBUG
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve

