name: Provision Tool Infra
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=infra-create/state.tf
      - name: Terraform Apply
        run: terraform apply -auto-approve

